"""
evaluate_model.py -- ML Validation & Benchmarking Suite
========================================================

Principal ML Security Engineer / Forensic Architect evaluation harness
for MITHYA's Isolation Forest anomaly detection engine.

Metrics Reported
----------------
- Precision, Recall, F1-Score (computed from pseudo-labels)
- False-Positive Rate (FPR) -- critical for operational deployments
- Median per-transaction Processing Time (us)
- Peak Memory Usage (MB via tracemalloc)

Dataset Categories
------------------
1. benign_traffic   -- exchanges & high-volume institutional transfers
2. known_threats    -- multi-hop peel chains, CoinJoin mixers, fee spikes
3. novel_threats    -- structurally novel obfuscation (fan-out, port reuse,
                       micro-dust dispersal) NOT seen in training distribution

Methodology
-----------
IsolationForest is an *unsupervised* model. To compute supervised metrics we
use *pseudo-labels*: transactions generated by each category are assigned a
ground-truth binary label (0 = benign, 1 = threat). The model is trained on a
combined corpus (simulating production deployment) and we measure its ability
to correctly flag threats vs. noise.

This mirrors real forensic validation practice (red-team / blue-team
classification against a labelled holdout set generated by the same synthetic
adversarial framework).

Usage
-----

    python evaluate_model.py
    python evaluate_model.py --records 500 --contamination 0.10 --verbose

"""

from __future__ import annotations

import argparse
import os
import sys
import time
import tracemalloc
import warnings
from typing import Dict, List, Tuple

import numpy as np
import pandas as pd

# Ensure project root is importable
sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))

warnings.filterwarnings("ignore", category=UserWarning)
warnings.filterwarnings("ignore", category=FutureWarning)

# ============================================================================
# Lazy imports
# ============================================================================

try:
    from sklearn.ensemble import IsolationForest
    from sklearn.metrics import (
        precision_score,
        recall_score,
        f1_score,
        confusion_matrix,
    )
except ImportError as exc:
    sys.exit(f"[!] scikit-learn required: {exc}")

try:
    from faker import Faker
except ImportError as exc:
    sys.exit(f"[!] faker required: {exc}")

# Optional: import MITHYA's own data generator for realistic features
try:
    from transaction_adapter import BitcoinCSVAdapter
    from ml_engine import engineer_features
    _HAS_ENGINE = True
except Exception:
    _HAS_ENGINE = False

# ============================================================================
# COLOUR CODES (ANSI) -- degrade gracefully on Windows / CI
# ============================================================================

_RESET  = "\033[0m"
_BOLD   = "\033[1m"
_RED    = "\033[91m"
_GREEN  = "\033[92m"
_YELLOW = "\033[93m"
_BLUE   = "\033[94m"
_CYAN   = "\033[96m"
_GREY   = "\033[90m"


def _c(text: str, colour: str) -> str:
    """Apply ANSI colour if stdout is a TTY."""
    if sys.stdout.isatty():
        return f"{colour}{text}{_RESET}"
    return text


# ============================================================================
# SYNTHETIC DATA GENERATORS
# ============================================================================

_SEED = 2026
_rng  = np.random.default_rng(_SEED)
fake  = Faker()
Faker.seed(_SEED)


def _btc_addr(prefix: str = "bc1q") -> str:
    """Generate a plausible-looking Bitcoin address."""
    chars = "0123456789abcdefghjklmnpqrstuvwxyz"
    tail  = "".join(_rng.choice(list(chars)) for _ in range(38))
    return f"{prefix}{tail}"


def _pipe(items: List) -> str:
    return "|".join(str(i) for i in items)


def _ts() -> str:
    return fake.date_time_between(start_date="-30d", end_date="now").isoformat(sep=" ")


def _src_ip() -> str:
    return fake.ipv4_public()


# ----------------------------------------------------------------------------
# 1. Benign Traffic (exchanges, high-volume normal users)
# ----------------------------------------------------------------------------

def generate_benign_traffic(n: int = 300) -> pd.DataFrame:
    """
    Simulate institutional / exchange-level normal transactions.

    Characteristics:
    - 1-3 inputs, 1-2 outputs
    - Moderate, round-ish amounts (exchange settlements)
    - Standard ports (8333, 443)
    - Low fee rate (sub-satoshi urgency)
    - Geo-diverse but ASN-coherent (major cloud ASNs)
    """
    records = []
    for _ in range(n):
        n_in  = int(_rng.integers(1, 4))
        n_out = int(_rng.integers(1, 3))
        in_addrs  = [_btc_addr("bc1q") for _ in range(n_in)]
        out_addrs = [_btc_addr("bc1q") for _ in range(n_out)]
        total     = round(float(_rng.uniform(0.1, 10.0)), 6)
        in_amts   = [round(total / n_in, 8)] * n_in
        out_amts  = [round(total * 0.99 / n_out, 8)] * n_out
        fee       = round(total * 0.001, 8)
        records.append({
            "timestamp":        _ts(),
            "txid":             fake.sha256(),
            "src_ip":           _src_ip(),
            "dst_ip":           _src_ip(),
            "src_port":         int(_rng.choice([8333, 443, 8332])),
            "dst_port":         int(_rng.choice([8333, 18333])),
            "input_addresses":  _pipe(in_addrs),
            "output_addresses": _pipe(out_addrs),
            "input_amounts":    _pipe(in_amts),
            "output_amounts":   _pipe(out_amts),
            "fee":              fee,
            "script_type":      "P2WPKH",
            "geo_country":      fake.country_code(),
            "asn":              f"AS{int(_rng.integers(1000, 65000))}",
            "_label":           0,  # BENIGN
        })
    return pd.DataFrame(records)


# ----------------------------------------------------------------------------
# 2. Known Threats (peel chains, mixers, fee spikes)
# ----------------------------------------------------------------------------

def generate_known_threats(n: int = 300) -> pd.DataFrame:
    """
    Simulate threat vectors the model WAS trained to detect:
    multi-hop peel chains, CoinJoin mixers, fee-spike hops.
    """
    records: List[Dict] = []
    per_type = max(1, n // 3)

    # 2a. Multi-hop peel chains
    for _ci in range(per_type):
        depth  = int(_rng.integers(3, 6))
        amount = round(float(_rng.uniform(0.5, 5.0)), 6)
        prev   = _btc_addr("bc1q")
        for hop in range(depth):
            next_addr = _btc_addr("bc1q")
            peel      = round(amount * 0.001, 8)
            amount   -= peel + 0.00001
            records.append({
                "timestamp":        _ts(),
                "txid":             fake.sha256(),
                "src_ip":           _src_ip(),
                "dst_ip":           _src_ip(),
                "src_port":         int(_rng.choice([9050, 9150])),
                "dst_port":         8333,
                "input_addresses":  prev,
                "output_addresses": _pipe([next_addr, _btc_addr("bc1q")]),
                "input_amounts":    str(round(amount + peel + 0.00001, 8)),
                "output_amounts":   _pipe([round(amount, 8), peel]),
                "fee":              round(0.00001 * (hop + 1), 8),
                "script_type":      "P2WPKH",
                "geo_country":      fake.country_code(),
                "asn":              f"AS{int(_rng.integers(1000, 65000))}",
                "_label":           1,
            })
            prev = next_addr
        if len(records) >= n:
            break

    # 2b. CoinJoin mixers
    for _ in range(min(per_type, n - len(records))):
        n_par = int(_rng.integers(10, 20))
        equal = round(float(_rng.uniform(0.01, 0.5)), 4)
        records.append({
            "timestamp":        _ts(),
            "txid":             fake.sha256(),
            "src_ip":           _src_ip(),
            "dst_ip":           _src_ip(),
            "src_port":         9050,
            "dst_port":         8333,
            "input_addresses":  _pipe([_btc_addr("1") for _ in range(n_par)]),
            "output_addresses": _pipe([_btc_addr("bc1q") for _ in range(n_par)]),
            "input_amounts":    _pipe([equal] * n_par),
            "output_amounts":   _pipe([equal] * n_par),
            "fee":              round(0.0001 * n_par, 8),
            "script_type":      "P2SH",
            "geo_country":      fake.country_code(),
            "asn":              f"AS{int(_rng.integers(1000, 65000))}",
            "_label":           1,
        })

    # 2c. Fee spike urgency hops
    for _ in range(min(per_type, n - len(records))):
        total = round(float(_rng.uniform(0.05, 1.0)), 6)
        fee   = round(total * 0.30, 8)
        records.append({
            "timestamp":        _ts(),
            "txid":             fake.sha256(),
            "src_ip":           _src_ip(),
            "dst_ip":           _src_ip(),
            "src_port":         int(_rng.choice([9050, 4444])),
            "dst_port":         8333,
            "input_addresses":  _btc_addr("bc1p"),
            "output_addresses": _btc_addr("bc1q"),
            "input_amounts":    str(total),
            "output_amounts":   str(round(total - fee, 8)),
            "fee":              fee,
            "script_type":      "P2TR",
            "geo_country":      fake.country_code(),
            "asn":              f"AS{int(_rng.integers(1000, 65000))}",
            "_label":           1,
        })

    return pd.DataFrame(records[:n])


# ----------------------------------------------------------------------------
# 3. Novel Threats (structurally unseen patterns)
# ----------------------------------------------------------------------------

def generate_novel_threats(n: int = 200) -> pd.DataFrame:
    """
    Simulate structurally novel obfuscation NOT explicitly coded in
    the training distribution heuristics. These stress-test the
    model's generalisation via feature density and statistical deviation.

    Includes:
    - Micro-dust dispersal (fan-out to 50+ addresses with sub-satoshi amounts)
    - I2P port reuse with unusual script-type mixing
    - Layered consolidation-and-split pattern
    """
    records: List[Dict] = []
    per_type = max(1, n // 3)

    # 3a. Micro-dust fan-out
    for _ in range(per_type):
        n_out = int(_rng.integers(50, 80))
        tiny  = round(0.00000547, 8)  # dust threshold
        records.append({
            "timestamp":        _ts(),
            "txid":             fake.sha256(),
            "src_ip":           _src_ip(),
            "dst_ip":           _src_ip(),
            "src_port":         4444,
            "dst_port":         8333,
            "input_addresses":  _btc_addr("1"),
            "output_addresses": _pipe([_btc_addr("bc1q") for _ in range(n_out)]),
            "input_amounts":    str(round(tiny * n_out * 1.01, 8)),
            "output_amounts":   _pipe([tiny] * n_out),
            "fee":              round(0.0001 * n_out, 8),
            "script_type":      "P2PKH",
            "geo_country":      fake.country_code(),
            "asn":              f"AS{int(_rng.integers(1000, 65000))}",
            "_label":           1,
        })

    # 3b. I2P consolidation sweep
    for _ in range(min(per_type, n - len(records))):
        n_in = int(_rng.integers(30, 60))
        records.append({
            "timestamp":        _ts(),
            "txid":             fake.sha256(),
            "src_ip":           _src_ip(),
            "dst_ip":           _src_ip(),
            "src_port":         4444,
            "dst_port":         4444,
            "input_addresses":  _pipe([_btc_addr("3") for _ in range(n_in)]),
            "output_addresses": _btc_addr("bc1p"),
            "input_amounts":    _pipe([
                round(float(_rng.uniform(0.001, 0.01)), 8) for _ in range(n_in)
            ]),
            "output_amounts":   str(round(float(_rng.uniform(0.05, 0.3)), 8)),
            "fee":              round(float(_rng.uniform(0.001, 0.01)), 8),
            "script_type":      "P2SH",
            "geo_country":      fake.country_code(),
            "asn":              f"AS{int(_rng.integers(1000, 65000))}",
            "_label":           1,
        })

    # 3c. Layered consolidate-and-split
    for _ in range(min(per_type, n - len(records))):
        n_in  = int(_rng.integers(5, 12))
        n_out = int(_rng.integers(8, 15))
        total = round(float(_rng.uniform(1.0, 10.0)), 6)
        records.append({
            "timestamp":        _ts(),
            "txid":             fake.sha256(),
            "src_ip":           _src_ip(),
            "dst_ip":           _src_ip(),
            "src_port":         int(_rng.choice([9050, 9150])),
            "dst_port":         int(_rng.choice([4444, 8333])),
            "input_addresses":  _pipe([_btc_addr("1") for _ in range(n_in)]),
            "output_addresses": _pipe([_btc_addr("bc1q") for _ in range(n_out)]),
            "input_amounts":    _pipe([round(total / n_in, 8)] * n_in),
            "output_amounts":   _pipe([round(total * 0.99 / n_out, 8)] * n_out),
            "fee":              round(total * 0.05, 8),
            "script_type":      "P2WPKH",
            "geo_country":      fake.country_code(),
            "asn":              f"AS{int(_rng.integers(1000, 65000))}",
            "_label":           1,
        })

    return pd.DataFrame(records[:n])


# ============================================================================
# FEATURE ENGINEERING (fallback when ml_engine is unavailable)
# ============================================================================

def _count_pipe(s) -> int:
    if not s or str(s).strip() in ("", "nan"):
        return 0
    return len([t for t in str(s).split("|") if t.strip()])


def _sum_pipe(s) -> float:
    if not s or str(s).strip() in ("", "nan"):
        return 0.0
    total = 0.0
    for t in str(s).split("|"):
        try:
            total += float(t.strip())
        except ValueError:
            pass
    return total


def _build_features_lightweight(df: pd.DataFrame) -> pd.DataFrame:
    """
    Lightweight feature extraction that does NOT require the full
    ml_engine graph pipeline. Used as a safe fallback for evaluation.

    Features (8):
    - fan_in, fan_out          : input/output address counts
    - total_amount             : sum of input amounts
    - fee_rate                 : fee / max(total_amount, 1e-9)
    - port_risk                : 1.0 if Tor/I2P port, else 0.0
    - equal_output_ratio       : fraction of outputs within 1% of mode
    - amount_diversity         : std-dev of output amounts (normalised)
    - io_ratio                 : fan_out / max(fan_in, 1)
    """
    TOR_I2P = {9050, 9051, 9150, 4444}

    feats = pd.DataFrame({
        "fan_in":       df["input_addresses"].apply(_count_pipe),
        "fan_out":      df["output_addresses"].apply(_count_pipe),
        "total_amount": df["input_amounts"].apply(_sum_pipe),
        "fee":          pd.to_numeric(df["fee"], errors="coerce").fillna(0.0),
        "port_risk":    df["src_port"].apply(
            lambda p: 1.0 if int(p) in TOR_I2P else 0.0
        ),
    })

    feats["fee_rate"] = feats["fee"] / feats["total_amount"].clip(lower=1e-9)
    feats["io_ratio"] = feats["fan_out"] / feats["fan_in"].clip(lower=1)

    def _equal_ratio(s) -> float:
        vals = []
        for t in str(s).split("|"):
            try:
                vals.append(float(t.strip()))
            except ValueError:
                pass
        if len(vals) < 2:
            return 0.0
        mode_val = max(
            set(round(v, 4) for v in vals),
            key=lambda v: sum(
                1 for x in vals if abs(x - v) / max(abs(v), 1e-9) < 0.01
            ),
        )
        equal_count = sum(
            1 for x in vals
            if abs(x - mode_val) / max(abs(mode_val), 1e-9) < 0.01
        )
        return equal_count / len(vals)

    feats["equal_output_ratio"] = df["output_amounts"].apply(_equal_ratio)

    def _amt_std(s) -> float:
        vals = []
        for t in str(s).split("|"):
            try:
                vals.append(float(t.strip()))
            except ValueError:
                pass
        if len(vals) < 2:
            return 0.0
        arr = np.array(vals)
        return float(np.std(arr) / max(np.mean(arr), 1e-9))

    feats["amount_diversity"] = df["output_amounts"].apply(_amt_std)
    return feats.fillna(0.0)


def build_features(df: pd.DataFrame) -> pd.DataFrame:
    """
    Attempt to use the full MITHYA ml_engine feature pipeline.
    Falls back to lightweight extraction if ml_engine is unavailable.
    """
    if _HAS_ENGINE:
        try:
            adapter = BitcoinCSVAdapter()
            df2 = adapter.normalize_addresses(df.copy())
            if not pd.api.types.is_datetime64_any_dtype(df2["timestamp"]):
                df2["timestamp"] = pd.to_datetime(df2["timestamp"], errors="coerce")
            feats, _ = engineer_features(df2)
            return feats.fillna(0.0)
        except Exception:
            pass
    return _build_features_lightweight(df)


# ============================================================================
# CORE EVALUATION ENGINE
# ============================================================================

class ModelEvaluator:
    """
    Trains an IsolationForest on a combined benign + threat corpus,
    then measures per-dataset and aggregate forensic metrics.
    """

    def __init__(
        self,
        n_estimators: int = 200,
        contamination: float = 0.10,
        random_state: int = _SEED,
        verbose: bool = False,
    ) -> None:
        self.n_estimators  = n_estimators
        self.contamination = contamination
        self.random_state  = random_state
        self.verbose       = verbose
        self.model: IsolationForest | None = None
        self._feature_cols: List[str] = []

    def fit(self, X_train: pd.DataFrame) -> None:
        """Train the IsolationForest on the given feature matrix."""
        self.model = IsolationForest(
            n_estimators=self.n_estimators,
            contamination=self.contamination,
            random_state=self.random_state,
            n_jobs=-1,
        )
        self._feature_cols = list(X_train.columns)
        self.model.fit(X_train[self._feature_cols])

    def _predict_timed(self, X: pd.DataFrame) -> Tuple[np.ndarray, float]:
        """
        Return (predictions_array, median_processing_time_us).
        Predictions: +1 = normal, -1 = anomaly -> flip to 1 = threat.
        """
        times = []
        preds = []
        X_vals = X[self._feature_cols].values
        for i in range(len(X_vals)):
            row = X_vals[i : i + 1]
            t0  = time.perf_counter_ns()
            p   = self.model.predict(row)[0]
            t1  = time.perf_counter_ns()
            preds.append(0 if p == 1 else 1)
            times.append((t1 - t0) / 1_000.0)  # ns -> us

        return np.array(preds, dtype=int), float(np.median(times))

    def evaluate_dataset(
        self,
        name: str,
        df: pd.DataFrame,
        true_labels: np.ndarray,
    ) -> Dict:
        """
        Run evaluation for a single named dataset and return a metrics dict.
        """
        assert self.model is not None, "Call fit() before evaluate_dataset()"

        X = build_features(df)
        for col in self._feature_cols:
            if col not in X.columns:
                X[col] = 0.0
        X = X[self._feature_cols].fillna(0.0)

        tracemalloc.start()
        pred_labels, median_us = self._predict_timed(X)
        _current, peak_bytes = tracemalloc.get_traced_memory()
        tracemalloc.stop()
        peak_mb = peak_bytes / (1024 ** 2)

        n_pos = int(true_labels.sum())
        n_neg = len(true_labels) - n_pos

        if n_pos == 0 or n_neg == 0:
            prec = rec = f1 = fpr = float("nan")
        else:
            prec = precision_score(true_labels, pred_labels, zero_division=0)
            rec  = recall_score(true_labels, pred_labels, zero_division=0)
            f1   = f1_score(true_labels, pred_labels, zero_division=0)
            tn, fp, fn, tp = confusion_matrix(
                true_labels, pred_labels, labels=[0, 1]
            ).ravel()
            fpr = fp / (fp + tn) if (fp + tn) > 0 else 0.0

        return {
            "dataset":        name,
            "n_total":        len(df),
            "n_threats":      n_pos,
            "n_benign":       n_neg,
            "precision":      prec,
            "recall":         rec,
            "f1_score":       f1,
            "fpr":            fpr,
            "median_time_us": median_us,
            "peak_mem_mb":    peak_mb,
            "pred_labels":    pred_labels,
            "true_labels":    true_labels,
        }


# ============================================================================
# REPORT RENDERING
# ============================================================================

_PASS_THRESH = {
    "precision": 0.70,
    "recall":    0.65,
    "f1_score":  0.65,
    "fpr":       0.20,   # FPR must be BELOW this threshold
}


def _fmt_metric(name: str, value: float) -> str:
    if np.isnan(value):
        return _c("  N/A (single-class dataset)", _GREY)

    thresh = _PASS_THRESH.get(name)
    if thresh is None:
        return f"  {value:.4f}"

    passed = (value <= thresh) if name == "fpr" else (value >= thresh)
    colour = _GREEN if passed else _RED
    marker = "PASS" if passed else "FAIL"
    return _c(f"  {value:.4f}  [{marker}]  threshold: {thresh:.2f}", colour)


def print_report(results: List[Dict], verbose: bool = False) -> None:
    width = 72
    print()
    print(_c("=" * width, _BLUE))
    print(_c("  MITHYA ML VALIDATION REPORT -- IsolationForest", _BOLD))
    print(_c("  Problem Statement 26146 | SIH 2026", _GREY))
    print(_c("=" * width, _BLUE))

    for res in results:
        print()
        print(_c(f"  > Dataset: {res['dataset']}", _CYAN + _BOLD))
        print(_c(f"  {'-' * (width - 4)}", _GREY))
        print(
            f"  Records          : {res['n_total']:,}  "
            f"({res['n_threats']:,} threats  /  {res['n_benign']:,} benign)"
        )
        print(f"  Precision        :{_fmt_metric('precision', res['precision'])}")
        print(f"  Recall           :{_fmt_metric('recall', res['recall'])}")
        print(f"  F1-Score         :{_fmt_metric('f1_score', res['f1_score'])}")
        print(f"  False-Pos Rate   :{_fmt_metric('fpr', res['fpr'])}")
        print(f"  Median Latency   :  {res['median_time_us']:.2f} us / transaction")
        print(f"  Peak Memory      :  {res['peak_mem_mb']:.3f} MB")

        if verbose and not np.isnan(res["f1_score"]):
            preds  = res["pred_labels"]
            labels = res["true_labels"]
            tp = int(((preds == 1) & (labels == 1)).sum())
            tn = int(((preds == 0) & (labels == 0)).sum())
            fp = int(((preds == 1) & (labels == 0)).sum())
            fn = int(((preds == 0) & (labels == 1)).sum())
            print()
            print("  Confusion Matrix :")
            print(f"    TP={tp:4d}  FP={fp:4d}")
            print(f"    FN={fn:4d}  TN={tn:4d}")

    print()
    print(_c(f"  {'-' * (width - 4)}", _GREY))
    print(_c("  AGGREGATE SUMMARY", _BOLD))

    valid = [r for r in results if not np.isnan(r["f1_score"])]
    if valid:
        avg_f1   = np.mean([r["f1_score"] for r in valid])
        avg_prec = np.mean([r["precision"] for r in valid])
        avg_rec  = np.mean([r["recall"] for r in valid])
        avg_fpr  = np.mean([r["fpr"] for r in valid])
        avg_lat  = np.mean([r["median_time_us"] for r in valid])
        max_mem  = max(r["peak_mem_mb"] for r in valid)

        print(f"  Avg Precision    :{_fmt_metric('precision', avg_prec)}")
        print(f"  Avg Recall       :{_fmt_metric('recall', avg_rec)}")
        print(f"  Avg F1-Score     :{_fmt_metric('f1_score', avg_f1)}")
        print(f"  Avg FPR          :{_fmt_metric('fpr', avg_fpr)}")
        print(f"  Avg Latency      :  {avg_lat:.2f} us / transaction")
        print(f"  Peak Memory      :  {max_mem:.3f} MB  (across all datasets)")

        passed = (
            avg_prec >= _PASS_THRESH["precision"]
            and avg_rec  >= _PASS_THRESH["recall"]
            and avg_f1   >= _PASS_THRESH["f1_score"]
            and avg_fpr  <= _PASS_THRESH["fpr"]
        )
        verdict = "OVERALL: PASS" if passed else "OVERALL: FAIL"
        colour  = _GREEN if passed else _RED
        print()
        print(_c(f"  {verdict}", colour + _BOLD))
    else:
        print(_c("  [!] No valid mixed-class results to aggregate.", _YELLOW))

    print(_c("=" * width, _BLUE))
    print()
    print(_c(
        "  FORENSIC DISCLAIMER\n"
        "  Scores are computed against synthetic pseudo-labels and represent\n"
        "  STATISTICAL ANOMALY DETECTION performance -- not calibrated guilt\n"
        "  probability. All flagged transactions require human analyst review.\n"
        "  IsolationForest output is INVESTIGATIVE PRIORITY, not legal evidence.",
        _YELLOW,
    ))
    print()


# ============================================================================
# MAIN
# ============================================================================

def main(args: argparse.Namespace) -> None:
    n             = args.records
    contamination = args.contamination
    verbose       = args.verbose

    print(_c(f"\n[*] Generating evaluation datasets (n={n} each)...", _BLUE))

    benign_df = generate_benign_traffic(n)
    known_df  = generate_known_threats(n)
    novel_df  = generate_novel_threats(n)

    print(_c("[*] Building feature matrices...", _BLUE))

    X_benign = build_features(benign_df)
    X_known  = build_features(known_df)
    X_novel  = build_features(novel_df)

    # Training corpus: benign + known threats (novel threats are holdout)
    X_train_raw = pd.concat([X_benign, X_known], ignore_index=True)

    # Align feature columns across all matrices
    all_cols = sorted(set(X_train_raw.columns) | set(X_novel.columns))
    for xdf in [X_train_raw, X_benign, X_known, X_novel]:
        for col in all_cols:
            if col not in xdf.columns:
                xdf[col] = 0.0

    X_train_raw = X_train_raw[all_cols].fillna(0.0)
    X_benign    = X_benign[all_cols].fillna(0.0)
    X_known     = X_known[all_cols].fillna(0.0)
    X_novel     = X_novel[all_cols].fillna(0.0)

    print(_c(
        f"[*] Training IsolationForest "
        f"(n_estimators=200, contamination={contamination})...",
        _BLUE,
    ))

    evaluator = ModelEvaluator(
        n_estimators=200,
        contamination=contamination,
        verbose=verbose,
    )
    evaluator.fit(X_train_raw)

    print(_c("[*] Evaluating on 3 dataset categories...", _BLUE))

    results = []

    results.append(evaluator.evaluate_dataset(
        "benign_traffic  (exchanges / high-volume normal users)",
        benign_df,
        benign_df["_label"].values,
    ))
    results.append(evaluator.evaluate_dataset(
        "known_threats   (peel chains / mixers / fee spikes)",
        known_df,
        known_df["_label"].values,
    ))
    results.append(evaluator.evaluate_dataset(
        "novel_threats   (dust dispersal / I2P sweep / consolidate-split)",
        novel_df,
        novel_df["_label"].values,
    ))

    print_report(results, verbose=verbose)


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description="MITHYA ML Validation & Benchmarking Suite",
        formatter_class=argparse.ArgumentDefaultsHelpFormatter,
    )
    parser.add_argument(
        "--records", type=int, default=300,
        help="Number of transactions per dataset category.",
    )
    parser.add_argument(
        "--contamination", type=float, default=0.10,
        help="IsolationForest contamination parameter.",
    )
    parser.add_argument(
        "--verbose", "-v", action="store_true",
        help="Print confusion matrices for each dataset.",
    )
    return parser.parse_args()


if __name__ == "__main__":
    main(parse_args())
